name: Build Binaries

on:
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup Linux
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config \
              libwayland-dev \
              libx11-xcb-dev \
              libxi-dev \
              libxkbcommon-dev \
              libxrandr-dev \
              libxinerama-dev \
              libxcursor-dev \
              mesa-common-dev 

      - name: Checkout
        uses: actions/checkout@v3

      - name: Init Submodules
        run: |
          git submodule update --init

      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: export/release/bin
